-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = {
        ["managed"] = {
            [1] = {
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 3440,
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "Tiling Frame<1>",
                                ["type"] = "WFrame",
                                ["mode"] = 1,
                            },
                        },
                        ["geom"] = {
                            ["h"] = 1440,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 3440,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<1>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["name"] = "WGroupWS<1>",
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["level"] = 0,
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 3440,
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1413,
                                                ["y"] = 24,
                                                ["x"] = 3,
                                                ["w"] = 1714,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 3,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 1413,
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1714,
                                                    },
                                                    ["windowid"] = 14680065,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["name"] = "WGroupCW<1>",
                                            ["type"] = "WGroupCW",
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["name"] = "Tiling Frame<2>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["sizepolicy"] = "full",
                                            ["level"] = 0,
                                            ["geom"] = {
                                                ["h"] = 1413,
                                                ["y"] = 24,
                                                ["x"] = 3,
                                                ["w"] = 1714,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["checkcode"] = 2,
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["h"] = 1404,
                                                        ["y"] = 4,
                                                        ["x"] = 2,
                                                        ["w"] = 1710,
                                                    },
                                                    ["windowid"] = 10485796,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WClientWin",
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["name"] = "WGroupCW",
                                            ["type"] = "WGroupCW",
                                            ["switchto"] = true,
                                        },
                                    },
                                    ["name"] = "Tiling Frame",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                            ["brs"] = 1720,
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1720,
                        },
                        ["geom"] = {
                            ["h"] = 1440,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 3440,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<5>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["name"] = "WGroupWS<5>",
                ["initial_outputs"] = {
                },
                ["switchto"] = true,
            },
            [3] = {
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 3440,
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                },
                                ["name"] = "WFrame<5>",
                                ["type"] = "WFrame",
                                ["mode"] = 1,
                            },
                        },
                        ["geom"] = {
                            ["h"] = 1440,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 3440,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<6>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["name"] = "WGroupWS<6>",
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
            },
        },
        ["name"] = "WScreen<1>",
        ["type"] = "WScreen",
    },
    [0] = {
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["level"] = 0,
                ["sizepolicy"] = "full",
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 2560,
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["type"] = "WSplitRegion",
                            ["regparams"] = {
                                ["managed"] = {
                                    [1] = {
                                        ["sizepolicy"] = "full",
                                        ["level"] = 0,
                                        ["geom"] = {
                                            ["h"] = 1413,
                                            ["y"] = 24,
                                            ["x"] = 3,
                                            ["w"] = 2554,
                                        },
                                        ["managed"] = {
                                            [1] = {
                                                ["checkcode"] = 1,
                                                ["bottom"] = true,
                                                ["geom"] = {
                                                    ["h"] = 1404,
                                                    ["y"] = 4,
                                                    ["x"] = 4,
                                                    ["w"] = 2547,
                                                },
                                                ["windowid"] = 27263012,
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WClientWin",
                                                ["level"] = 1,
                                            },
                                        },
                                        ["name"] = "WGroupCW<2>",
                                        ["type"] = "WGroupCW",
                                        ["switchto"] = true,
                                    },
                                },
                                ["name"] = "WFrame<3>",
                                ["type"] = "WFrame",
                                ["mode"] = 1,
                            },
                        },
                        ["geom"] = {
                            ["h"] = 1440,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 2560,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<3>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["name"] = "WGroupWS<3>",
                ["initial_outputs"] = {
                },
                ["switchto"] = true,
            },
            [2] = {
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["level"] = 0,
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 2560,
                },
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<4>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<2>",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                            ["brs"] = 1280,
                            ["type"] = "WSplitSplit",
                            ["tls"] = 1280,
                        },
                        ["geom"] = {
                            ["h"] = 1440,
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 2560,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<4>",
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                    },
                },
                ["name"] = "WGroupWS<4>",
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["geom"] = {
                    ["h"] = 1440,
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 2560,
                },
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["sizepolicy"] = "free_glue",
                        ["level"] = 1025,
                        ["geom"] = {
                            ["h"] = 480,
                            ["y"] = 960,
                            ["x"] = 400,
                            ["w"] = 640,
                        },
                        ["managed"] = {
                        },
                        ["mode"] = 0,
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                    },
                },
                ["name"] = "*scratchws*",
                ["type"] = "WGroupWS",
                ["level"] = 1,
                ["pseudomodal"] = true,
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["unnumbered"] = true,
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

